# --------------------------------------------------
# Site Settings
# --------------------------------------------------

# Menu
menu:
  home: / || 首页
  galleries: /galleries/ || 画廊
  archives: /archives/ || 归档
  tags: /tags/ || 标签
  categories: /categories/ || 分类
  about: /about/ || 关于

# Color
color:
  text: '#33333D'
  text-secondary: '#4e4e4e'
  text-third: '#999999'
  background: '#ffffff'
  background-secondary: '#f6f8fa'
  border: '#eeeeee'
  text-dark: '#dddddd'
  text-secondary-dark: '#9899ab'
  text-third-dark: '#7d8594'
  background-dark: '#1e2128'
  background-secondary-dark: '#1a1d22'
  border-dark: '#2b3038'
  link: '#FF3B00'
  link-gradient: 'linear-gradient(-60deg, #ff5858 0%, #f09819 100%)'

# Favicon
favicon:
  small: /images/icons/favicon-16x16.ico
  medium: /images/icons/favicon-32x32.ico
  apple_touch_icon: /images/icons/apple-touch-icon.jpeg
  safari_pinned_tab: /images/icons/stun-logo.svg
  msapplication: /images/icons/favicon-128x128.ico

# Font
font:
  size: 14px
  family:

# Background Image
background_image:

# Loading
loading:
  gif: /images/theme/loading.gif
  lottie:

# Preview
preview:
  enable: true
  type: wave  # wave | cloud
  background:
    type: image # image video
    default_image:
      light: /images/theme/welcome-image.jpg
      dark: /images/theme/welcome-image.jpg
    video:
    api: https://source.unsplash.com/random/1920x1080
    size: cover # css: background-size
    position: center # css: background-position
  motto:
    default: 我在开了灯的床头下，想问问自己的心啊。
    color: '#ffffff'
    typing: true
    api: https://v2.jinrishici.com/one.json
    data_contents: ['data', 'content']
    # ex.one  =>  apl: https://v1.hitokoto.cn/?encode=text&c=i  data_contents:
    # ex.two  =>  api: https://v2.jinrishici.com/one.json  data_contents: ['data', 'content']

# Navbar
navbar:
  enable: true
  back_home: true

# Copyright
copyright: <p> Powered by <a target="_blank" href="https://hexo.io">Hexo</a>  |  Theme - <a target="_blank" href="https://github.com/izhaoo/hexo-theme-zhaoo">zhaoo</a></p> <p>Cherry White .All Rights Reserved Copyright © 2021 </p>

# Social
social:
  qq: tencent://message/?Menu=yes&uin=1789139001 || iconQQ || '#12B7F5'
  wechat: /images/contact/wechat.jpg || iconwechat-fill || '#09BB07'
  instagram: https://cherry-white.github.io/ || iconinstagram || '#DA2E76'
  github: https://gitee.com/zj1789139001 || icongithub-fill || '#9f7be1'
  email: mailto:1789139001@qq.com || iconmail
# Override Scrollbar
scrollbar:
  type: simple # default | simple | normal | none

# Fab (Float Action Button)
fab:
  enable: true
  always_show: false

# Search https://github.com/wzpan/hexo-generator-search
search:
  enable: true

# QR Code
qrcode:
  enable: true
  type: url # url | image
  image: https://pic.izhaoo.com/weapp-code.jpg

# Color Mode
color_mode:
  enable: true

# Gray (Mourning Mode)
gray:
  enable: false

# --------------------------------------------------
# Post Settings
# --------------------------------------------------

# Excerpt
excerpt:
  enable: true

# Post Image 不添加封面图片时，会显示默认图片
post_image:
  random: local # local galleries
  default: /images/background/default.jpg # 设置默认封面图片

# Page Size
post_page_size:
  width: 800px

# Caption
caption:
  enable: true

# Indent
indent:
  content:
  excerpt:

# TOC
toc:
  enable: true
  always_show: true
  min_depth: 1
  max_depth: 3

# Donate
donate:
  enable: true
  alipay: /images/pay/alipay.png
  wechat: /images/pay/wechat.jpg

# Copyright
post_copyright:
  enable: true

# Carrier（copy article with one click）
carrier:
  enable: true
  type: html # html | markdown | text

# --------------------------------------------------
# Page Settings
# --------------------------------------------------

# Galleries
galleries:
  enable: true
  title: 画廊
  subtitle: Photography
  type: waterfall # waterfall | grid
  columns: 3


# --------------------------------------------------
# Comment Settings
# --------------------------------------------------

comments:
  enable: false
  type: gitalk # gitalk | valine | changyan
  button: true

# Gitalk
gitalk:
  owner: cherry-white
  repo: cherry-white.github.io
  admin: ['cherry-white']
  clientID: 5d2553717eea46759e10
  clientSecret: 4d93ce39e65dd2c5b9e364f75d06efd73c64a8ba
  proxy: /githubAgent/login/oauth/access_token

# Valine
valine:
  appId:
  appKey:
  placeholder: 雁过留痕
  avatar: mp
  pageSize: 10
  lang: zh-CN

# ChangYan
changyan:
  appId:
  conf:

# --------------------------------------------------
# Plugin settings
# --------------------------------------------------

# Notification
notification:
  enable: false
  delay: 4500
  page_white_list:
  page_black_list:

# Daovoice
daovoice:
  enable: false
  appId: # app_id

# Tencent Chao
tencentChao:
  enable: true
  appId: 368715

# LeanCloud
leancloud:
  enable: false
  appId:
  appKey:
  serverURLs: https://leancloud.cn/

# Lazyload
lazyload:
  enable: true
  only_post: false
  loading:
    gif: /images/theme/loading.gif
    lottie:

# FancyBox
fancybox: true

# Pjax
pjax: false

# HighLight
highlight:
  enable: true
  style: # https://highlightjs.org/static/demo/
    light: Monokai  # Xcode
    dark: Solarized Dark

# SEO
seo:
  baidu_auto_push: true

# Analytics
analytics:
  baidu: 3cbbee458915615f7e2e5b7a073f2113 # id
  google: # id
  tencent: # id
  cnzz: # id

# --------------------------------------------------
# Script Settings
# --------------------------------------------------

# CDN 对于外部静态文件（CSS 或 JS），可以使用第三方 `CDN` 库进行加速。在主题配置文件中填写相应的 `URL` 即可配置，你可以使用默认值（BootCDN），留空则使用本地 `lib` 目录下的文件。
vendors:
  jquery_js:
  fancybox_js:
  pjax_js:
  lazyload_js:
  qrcode_js:
  daovoice_js:
  lottie_js:
  gitalk_js:
  gitalk_css:
  fancybox_css:
  highlight_css:
  iconfont_css:

# Custom
custom:
  # 头部埋点
  head:
  # 尾部埋点
  foot:
  css:
  js:
